---
name: Build LaTeX PDFs
"on":
  push:
    paths:
      - '**.tex'
      - 'lecture/build.py'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Initialize and update submodules
        run: |
          git submodule update --init --recursive
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |  # runs build.py with submodule location and builds PDF
            cd lecture
            cp ../course_template/lectureClass.cls ./
            python3 build.py
            cd ..

      - name: Upload PDF file
        uses: actions/upload-pages-artifact@v3  # actions/upload-artifact@v4
        with:
          name: github-pages
          path: built/


  deploy:
    needs: build_latex

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
